server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod



#person:
#  name: gx
#  age: 12
#  boss: true
#  birth: 2020/02/02
#  maps: {k1: v1,k2: valsss1}
#  list:
#   - lisi
#   - zhaoliu
#  dog:
#    name: tom
#    age: 11

